project_id = "vbaaohcsmiaxbqcyfhhl"

[functions.transcribe]
verify_jwt = false

[functions.generate-annotation]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
